### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by yongsan-tao** [EmirioBomb/zgc-ems#4]
你好，可以提供一下招聘项目的建表语句吗？

**Comment by EmirioBomb** [comment]
抱歉，该项目的建表语句已经找不到了，或许可参考README中的E-R关系映射

**Comment by yongsan-tao** [comment]
> 抱歉，该项目的建表语句已经找不到了，或许可参考README中的E-R关系映射

好的，谢谢了！
